# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12test_message.proto\"\x95\x02\n\x0bTestMessage\x12\x0c\n\x04strT\x18\x01 \x01(\t\x12\x0c\n\x04intT\x18\x02 \x01(\r\x12\x0e\n\x06\x66loatT\x18\x03 \x01(\x01\x12\x11\n\tarrayIntT\x18\x04 \x03(\x05\x12\x11\n\tarrayStrT\x18\x05 \x03(\t\x12-\n\ndictFloatT\x18\x06 \x01(\x0b\x32\x19.TestMessage.Dict_float_t\x12)\n\x08\x64ictStrT\x18\x07 \x01(\x0b\x32\x17.TestMessage.Dict_str_t\x1a-\n\x0c\x44ict_float_t\x12\r\n\x05\x66irst\x18\x01 \x01(\x01\x12\x0e\n\x06second\x18\x02 \x01(\x01\x1a+\n\nDict_str_t\x12\r\n\x05\x66irst\x18\x01 \x01(\t\x12\x0e\n\x06second\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TESTMESSAGE']._serialized_start=23
  _globals['_TESTMESSAGE']._serialized_end=300
  _globals['_TESTMESSAGE_DICT_FLOAT_T']._serialized_start=210
  _globals['_TESTMESSAGE_DICT_FLOAT_T']._serialized_end=255
  _globals['_TESTMESSAGE_DICT_STR_T']._serialized_start=257
  _globals['_TESTMESSAGE_DICT_STR_T']._serialized_end=300
# @@protoc_insertion_point(module_scope)
